// import "./chapter1/01_appendText"
// import "./chapter1/02_appendParagraphs"
// import "./chapter2/01_appendBar"
// import "./chapter2/02_appendBarDradHeight"
// import "./chapter2/03_appendBarRandomData"
// import "./chapter2/04_appendBarRandomi"
// import "./chapter3/01_svg"
// import "./chapter3/02_svgRect"
// import "./chapter3/03_chart_bar"
// import "./chapter3/04_chart_bar_rect"
// import "./chapter3/05_chart_bar_rect _even"
// import "./chapter3/06_chart_bar_rect _even widths"
import "./chapter3/07_making_a_bar_chart_heights.html"